######################## default configuration ####################
baseURL = "https://www.osteopathiekammhoff.de"
title = "Osteopathie Maren Kammhoff"
theme = "persian"
languageName = "de"
languageCode = "de-DE"
defaultLanguage = 'de'
defaultContentLanguage = 'de'

############################# output ##############################
[outputs]
home = ["HTML", "RSS", "json", "sitemap"]


# render unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"


################################ languages de #############################
[languages]
[languages.de]
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = '🇩🇪'
    weight = 1

################################ menu de ##################################
[languages.de.menus]
[[languages.de.menus.main]]
name = "Osteopathie"
url = "osteopathie"
weight = 1  

[[languages.de.menus.main]]
name = "Behandlung/Kosten"
url = "behandlung"
weight = 2

[[languages.de.menus.main]]
name = "Über Mich"
url = "about"
weight = 3

[[languages.de.menus.main]]
name = "Praxis"
url = "praxis"
weight = 4

[[languages.de.menus.main]]
name = "Kontakt"
url = "kontakt"
weight = 5

[[languages.de.menus.main]]
name = "Impressum"
url = "datenschutz"
weight = 6

################################ languages en #############################

[languages.en]
    languageCode = 'en-EN'
    languageDirection = 'ltr'
    languageName = '🇬🇧'
    weight = 0

################################ menu en ##################################
[languages.en.menus] 

[[languages.en.menus.main]]
name = "Osteopathy"
url = "/en/osteopathie"
weight = 1  

[[languages.en.menus.main]]
name = "Treatment/Costs"
url = "behandlung"
weight = 2

[[languages.en.menus.main]]
name = "About"
url = "about"
weight = 3

[[languages.en.menus.main]]
name = "Praxis"
url = "praxis"
weight = 4

[[languages.en.menus.main]]
name = "Contact"
url = "kontakt"
weight = 5

[[languages.en.menus.main]]
name = "Imprint"
url = "datenschutz"
weight = 6

################################ languages fr #############################

[languages.fr]
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = '🇫🇷'
    weight = 0

################################ menu fr ##################################
[languages.fr.menus] 

[[languages.fr.menus.main]]
name = "Ostéopathie"
url = "osteopathie"
weight = 1  

[[languages.fr.menus.main]]
name = "Traitement/Coûts"
url = "behandlung"
weight = 2

[[languages.fr.menus.main]]
name = "À propos"
url = "about"
weight = 3

[[languages.fr.menus.main]]
name = "Cabinet"
url = "praxis"
weight = 4

[[languages.fr.menus.main]]
name = "Contact"
url = "kontakt"
weight = 5

[[languages.fr.menus.main]]
name = "Mentions Légales"
url = "datenschutz"
weight = 6

################################ languages es #############################

[languages.es]
    languageCode = 'es-ES'
    languageDirection = 'ltr'
    languageName = '🇪🇸'
    weight = 0

################################ menu es ##################################
[languages.es.menus] 

[[languages.es.menus.main]]
name = "Osteopatía"
url = "osteopathie"
weight = 1  

[[languages.es.menus.main]]
name = "Tratamiento/Costos"
url = "behandlung"
weight = 2

[[languages.es.menus.main]]
name = "Acerca de"
url = "about"
weight = 3

[[languages.es.menus.main]]
name = "Consulta"
url = "praxis"
weight = 4

[[languages.es.menus.main]]
name = "Contacto"
url = "kontakt"
weight = 5

[[languages.es.menus.main]]
name = "Aviso Legal"
url = "datenschutz"
weight = 6


#################### default parameters ################################
[params]
# logo = "images/logo.png"
# Meta data
description = "Willkommen in Ihrer Osteopathie-Praxis für die gesamte Familie. Spezialisiert auf Säuglinge, Kinder und Schwangere sowie Frauen nach der Geburt. Erwachsene jeden Alters sind auch herzlich willkommen. Welcome to your osteopathy practice for the entire family. Specializing in infants, children, and pregnant women, as well as women after childbirth. Adults of all ages are also warmly welcome."
author = "Maren Kammhoff"
# search  
search = true
# contact form action
contact_form_action = "https://formspree.io/f/mzbybqzl" # contact form works with https://formspree.io
# copyright
copyright = "Copyright © 2024 Maren Kammhoff Osteopathie. All rights reserved."
# contact_info
contact_info = "Kontakt: +491779244251 | maren@osteopathiekammhoff.de"
# adress
address = "Adresse: Kelterstraße 50, 70199 Stuttgart"
# hours
hours = "Öffnungszeiten: Mo. - Fr: 09:00-13:00 + 14:00-18:00. Weitere Termine nach Vereinbarung"
# social media
linkedin_url = "https://www.linkedin.com/in/maren-kammhoff-62b912b4/"
instagram_url = "https://www.instagram.com/osteopathiemarenkammhoff/"

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Search engines
enableRobotsTXT = true

