######################## default configuration ####################
baseURL = "https://www.osteopathiekammhoff.de"
title = "Osteopathie Kammhoff"
theme = "persian"
languageName = "de"
languageCode = "de-DE"
defaultLanguage = 'de'
defaultContentLanguage = 'de'

############################# output ##############################
[outputs]
home = [ "HTML", "RSS", "json"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"


################################ languages de #############################
[languages]
[languages.de]
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    weight = 1

################################ menu de ##################################
[languages.de.menus]

[[languages.de.menus.main]]
name = "Osteopathie"
url = "/"
weight = 1  

[[languages.de.menus.main]]
name = "Behandlung/Kosten"
url = "behandlung"
weight = 2

[[languages.de.menus.main]]
name = "Über Mich"
url = "about"
weight = 3

[[languages.de.menus.main]]
name = "Praxis"
url = "praxis"
weight = 4

[[languages.de.menus.main]]
name = "Kontakt"
url = "kontakt"
weight = 5

[[languages.de.menus.main]]
name = "Impressum"
url = "datenschutz"
weight = 6

################################ languages en #############################

[languages.en]
    languageCode = 'en-EN'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 0

################################ menu en ##################################
[languages.en.menus] 

[[languages.en.menus.main]]
name = "Treatment/Costs"
url = "behandlung"
weight = 2

[[languages.en.menus.main]]
name = "About"
url = "about"
weight = 3

[[languages.en.menus.main]]
name = "Praxis"
url = "praxis"
weight = 4

[[languages.en.menus.main]]
name = "Contact"
url = "kontakt"
weight = 5

[[languages.en.menus.main]]
name = "Impressum"
url = "datenschutz"
weight = 6

################################ languages fr #############################

[languages.fr]
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'French'
    weight = 0

################################ menu fr ##################################
[languages.fr.menus] 

[[languages.fr.menus.main]]
name = "Traitement/Coûts"
url = "behandlung"
weight = 2

[[languages.fr.menus.main]]
name = "À propos"
url = "about"
weight = 3

[[languages.fr.menus.main]]
name = "Cabinet"
url = "praxis"
weight = 4

[[languages.fr.menus.main]]
name = "Contact"
url = "kontakt"
weight = 5

[[languages.fr.menus.main]]
name = "Impressum"
url = "datenschutz"
weight = 6


#################### default parameters ################################
[params]
# logo = "images/logo.png"
# Meta data
description = "Discover holistic osteopathic care at our Berlin practice. Specializing in chronic pain, acute injuries, and overall wellness, we offer personalized treatments in a welcoming environment. Visit us for expert osteopathy services tailored to your needs. Entdecken Sie ganzheitliche osteopathische Betreuung in unserer Berliner Praxis. Wir sind spezialisiert auf chronische Schmerzen, akute Verletzungen und allgemeines Wohlbefinden. Besuchen Sie uns für individuell angepasste Behandlungen in einer einladenden Umgebung."
author = "Maren Kammhoff"
# search  
search = true
# contact form action
contact_form_action = "https://formspree.io/f/mzbybqzl" # contact form works with https://formspree.io
# copyright
copyright = "Copyright © 2024 Maren Kammhoff Osteopathie. All rights reserved."

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Search engines
enableRobotsTXT = true