[build]
  publish = "osteopathieKammhoff/public"
  command = "cd osteopathieKammhoff && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_THEME = "persian"
  HUGO_BASEURL = "/"